// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://metuvjhbcsxtqvzhxrhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ldHV2amhiY3N4dHF2emh4cmhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzczOTksImV4cCI6MjA2MDU1MzM5OX0.Eh4IdIbd_oU3CjLgx6DB7Y3MKnjFYZy7kQylmMAMPCw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);